apiVersion: v1
kind: Service
metadata:
  name: redis-cluster
spec:
  ports:
    - port: 6380
      name: client
  clusterIP: None
  selector:
    app: redis-cluster

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-cluster
spec:
  serviceName: "redis-cluster"
  replicas: 3
  selector:
    matchLabels:
      app: redis-cluster
  template:
    metadata:
      labels:
        app: redis-cluster
    spec:
      containers:
        - name: redis
          image: redis:6.2
          command:
            - "redis-server"
            - "--appendonly"
            - "yes"
            - "--cluster-enabled"
            - "yes"
          ports:
            - containerPort: 6380
              name: client
